name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python dsronne_com/manage.py test
          
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLAY_PRIVATE_KEY }}
  
      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H dsronne.com >> ~/.ssh/known_hosts
      - name: Deploy to Server
        run: |
          rsync -avz --delete --exclude-from='- .gitignore' ./ vextorspace@dsronne.com:~/dsronne.com

